# Generated by Django 5.2.3 on 2025-06-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True)),
                ('live_demo', models.URLField(blank=True)),
                ('tech_stack', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
